name: WebApp4 CI
on: [pull_request]
jobs:
  build-react:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: WebApplication4/wwwroot/spa
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Install dependencies
        run: npm ci
      - run: npm run build-custom
      - run: npm test

  deploy:
    needs: [build-react]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: webapp-classwork
          heroku_email: rubleuskia@gmail.com